const List = [
  {
    id: 1,
    name: "Adenium",
    price: 250,
    category: "High Maintenance",
    image: "IndoorPlants/Adenium.jpg",
    route: "/",
  },
  {
    id: 2,
    name: "Barleria",
    price: 800,
    category: "Medium Maintenance",
    image: "IndoorPlants/Barleria.jpg",
    route: "/",
  },
  {
    id: 3,
    name: "Nicodiamini",
    price: 300,
    category: "Low Maintenance",
    image: "IndoorPlants/Nicodiamini.jpg",
    route: "/",
  },
  {
    id: 4,
    name: "Jacobina",
    price: 550,
    category: "High Maintenance",
    image: "IndoorPlants/Jacobina.jpg",
    route: "/",
  },
  {
    id: 5,
    name: "Roheo Variegated",
    price: 400,
    category: "Medium Maintenance",
    image: "IndoorPlants/RoheoVariegated.jpg",
    route: "/",
  },
  {
    id: 6,
    name: "Ficus Starlight",
    price: 350,
    category: "Low Maintenance",
    image: "IndoorPlants/FicusStarlight.jpg",
    route: "/",
  },
  {
    id: 7,
    name: "Ficus",
    price: 900,
    category: "High Maintenance",
    image: "IndoorPlants/Ficus.jpg",
    route: "/",
  },
  {
    id: 8,
    name: "Euphorbia Pink",
    price: 600,
    category: "Medium Maintenance",
    image: "IndoorPlants/EuphorbiaPink.jpg",
    route: "/",
  },
  {
    id: 9,
    name: "Eranthemum Gold",
    price: 450,
    category: "Low Maintenance",
    image: "IndoorPlants/EranthemumGold.jpg",
    route: "/",
  },
  {
    id: 10,
    name: "Peace Lily",
    price: 700,
    category: "Medium Maintenance",
    image: "IndoorPlants/PeaceLily.jpg",
    route: "/",
  },
  {
    id: 11,
    name: "Spider Plant",
    price: 500,
    category: "Low Maintenance",
    image: "IndoorPlants/SpiderPlant.jpg",
    route: "/",
  },
  {
    id: 12,
    name: "Areca Palm",
    price: 750,
    category: "High Maintenance",
    image: "IndoorPlants/ArecaPalm.jpg",
    route: "/",
  },
  {
    id: 13,
    name: "ZZ Plant",
    price: 650,
    category: "Low Maintenance",
    image: "IndoorPlants/ZZPlant.jpg",
    route: "/",
  },
  {
    id: 14,
    name: "Snake Plant",
    price: 480,
    category: "Low Maintenance",
    image: "IndoorPlants/SnakePlant.jpg",
    route: "/",
  },
  {
    id: 15,
    name: "Philodendron",
    price: 820,
    category: "High Maintenance",
    image: "IndoorPlants/Philodendron.jpg",
    route: "/",
  },
];

export default List;
