const OutdoorPlants = [
  {
    id: 1,
    name: "Bougainvillea",
    price: 300,
    category: "High Maintenance",
    image: "OutdoorPlants/Bougainvillea.jpg",
    route: "/",
  },
  {
    id: 2,
    name: "Jade Plant",
    price: 450,
    category: "Low Maintenance",
    image: "OutdoorPlants/JadePlant.jpg",
    route: "/",
  },
  {
    id: 3,
    name: "Chrysanthemum",
    price: 500,
    category: "Medium Maintenance",
    image: "OutdoorPlants/Chrysanthemum.jpg",
    route: "/",
  },
  {
    id: 4,
    name: "Hibiscus",
    price: 600,
    category: "Medium Maintenance",
    image: "OutdoorPlants/Hibiscus.jpg",
    route: "/",
  },
  {
    id: 5,
    name: "Marigold",
    price: 250,
    category: "Low Maintenance",
    image: "OutdoorPlants/Marigold.jpg",
    route: "/",
  },
  {
    id: 6,
    name: "Palm Tree",
    price: 1200,
    category: "High Maintenance",
    image: "OutdoorPlants/PalmTree.jpg",
    route: "/",
  },
  {
    id: 7,
    name: "Croton",
    price: 550,
    category: "Medium Maintenance",
    image: "OutdoorPlants/Croton.jpg",
    route: "/",
  },
  {
    id: 8,
    name: "Fountain Grass",
    price: 800,
    category: "Low Maintenance",
    image: "OutdoorPlants/FountainGrass.jpg",
    route: "/",
  },
  {
    id: 9,
    name: "Lavender",
    price: 650,
    category: "Low Maintenance",
    image: "OutdoorPlants/Lavender.jpg",
    route: "/",
  },
  {
    id: 10,
    name: "Aloe Vera",
    price: 400,
    category: "Low Maintenance",
    image: "OutdoorPlants/AloeVera.jpg",
    route: "/",
  },
  {
    id: 11,
    name: "Sunflower",
    price: 480,
    category: "Medium Maintenance",
    image: "OutdoorPlants/Sunflower.jpg",
    route: "/",
  },
  {
    id: 12,
    name: "Money Plant",
    price: 700,
    category: "Low Maintenance",
    image: "OutdoorPlants/MoneyPlant.jpg",
    route: "/",
  },
  {
    id: 13,
    name: "Cactus",
    price: 320,
    category: "Low Maintenance",
    image: "OutdoorPlants/Cactus.jpg",
    route: "/",
  },
  {
    id: 14,
    name: "Areca Palm",
    price: 850,
    category: "High Maintenance",
    image: "OutdoorPlants/ArecaPalm.jpg",
    route: "/",
  },
  {
    id: 15,
    name: "Gardenia",
    price: 780,
    category: "High Maintenance",
    image: "OutdoorPlants/Gardenia.jpg",
    route: "/",
  },
];

export default OutdoorPlants;
