"use client"
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/app/ui/Components/Footer";
import NavBar from "@/app/ui/Components/Navbar";
import {AuthContextProvider} from "../lib/context/AuthContent";

// export const metadata: Metadata = {
//   title: "Green Haven",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AuthContextProvider>
        <NavBar /> 
        {children}
        <Footer />
        </AuthContextProvider>
      </body>
    </html>
  );
}
