import type { Metadata } from "next";
import "./globals.css";
import Footer from "./Components/Footer";
import NavBar from "./Components/Navbar";

export const metadata: Metadata = {
  title: "Green Haven",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <NavBar /> 
        {children}
        <Footer />
      </body>
    </html>
  );
}
