const FloweringPlants = [
    {
      id: 1,
      name: "Rose",
      price: 350,
      category: "High Maintenance",
      image: "FloweringPlants/Rose.jpg",
      route: "/",
    },
    {
      id: 2,
      name: "Hibiscus",
      price: 500,
      category: "Medium Maintenance",
      image: "FloweringPlants/Hibiscus.jpg",
      route: "/",
    },
    {
      id: 3,
      name: "Jasmine",
      price: 400,
      category: "Low Maintenance",
      image: "FloweringPlants/Jasmine.jpg",
      route: "/",
    },
    {
      id: 4,
      name: "Marigold",
      price: 280,
      category: "Low Maintenance",
      image: "FloweringPlants/Marigold.jpg",
      route: "/",
    },
    {
      id: 5,
      name: "Daisy",
      price: 450,
      category: "Medium Maintenance",
      image: "FloweringPlants/Daisy.jpg",
      route: "/",
    },
    {
      id: 6,
      name: "Lotus",
      price: 900,
      category: "High Maintenance",
      image: "FloweringPlants/Lotus.jpg",
      route: "/",
    },
    {
      id: 7,
      name: "Orchid",
      price: 1200,
      category: "High Maintenance",
      image: "FloweringPlants/Orchid.jpg",
      route: "/",
    },
    {
      id: 8,
      name: "Tulip",
      price: 800,
      category: "Medium Maintenance",
      image: "FloweringPlants/Tulip.jpg",
      route: "/",
    },
    {
      id: 9,
      name: "Lavender",
      price: 650,
      category: "Low Maintenance",
      image: "FloweringPlants/Lavender.jpg",
      route: "/",
    },
    {
      id: 10,
      name: "Sunflower",
      price: 550,
      category: "Medium Maintenance",
      image: "FloweringPlants/Sunflower.jpg",
      route: "/",
    },
    {
      id: 11,
      name: "Chrysanthemum",
      price: 600,
      category: "Medium Maintenance",
      image: "FloweringPlants/Chrysanthemum.jpg",
      route: "/",
    },
    {
      id: 12,
      name: "Bougainvillea",
      price: 420,
      category: "Low Maintenance",
      image: "FloweringPlants/Bougainvillea.jpg",
      route: "/",
    },
    {
      id: 13,
      name: "Daffodil",
      price: 750,
      category: "Medium Maintenance",
      image: "FloweringPlants/Daffodil.jpg",
      route: "/",
    },
    {
      id: 14,
      name: "Gardenia",
      price: 720,
      category: "High Maintenance",
      image: "FloweringPlants/Gardenia.jpg",
      route: "/",
    },
    {
      id: 15,
      name: "Peony",
      price: 850,
      category: "High Maintenance",
      image: "FloweringPlants/Peony.jpg",
      route: "/",
    },
  ];
  
  export default FloweringPlants;
  